#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

gdb -nx --batch -x $DIR/gai-gdb -f $1 2> /tmp/gai__gdb_err.txt  | \
  sed 's/^Z//g' | sed 's/\t/  /g'                               | \
  $DIR/gai-js
